# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  solid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
          architecture: x64
      - name: Test Solid
        run: cd solid && mvn -B package --file pom.xml
  matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
          architecture: x64
      - name: Test Maxrix
        run: cd matrix && mvn -B package --file pom.xml
  abstractfactory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14.0.2'
          architecture: x64
      - name: Test AbstractFactory
        run: cd abstractfactory && mvn -B package --file pom.xml
